jenny/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('street.urls', namespace='street')),
    # path(r'fontawesome/',include('django_static_fontawesome.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

street/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . views import (LoginPage,home_view, logout_view,client_dashboard,approval,
gift_card,upload_card,AboutUs,hustler_dashboard,Withdraw,approve_front,approve_back,register,
viewActive,quiz_expired,withdraw_time_extension)

app_name = 'street'
urlpatterns =[
    path('login/',LoginPage,name='login'),
	path('logout/', logout_view, name='logout'), 
    path('user/dashboard/', client_dashboard, name='client'), 
    path('oga/dashboard', hustler_dashboard, name='hustler'),
    path('amount/withdraw/', Withdraw, name='withdraw'),
    path('card_choice/', gift_card, name='gift_card'), 
    path('upload_card/', upload_card, name='upload_card'), 
    path(r'', home_view, name='home'),
    path('about_page/', AboutUs, name='about'),
    path('approve/front/<int:card_id>/', approve_front, name='approve_front'),
    path('approve/back/<int:card_id>/', approve_back, name='approve_back'),
    path('user_details/<int:id>/', viewActive, name='user_active'),
    path('new_user/', register, name='register'),
    path('approval/', approval, name='approval'),
    path('time_elasped/continue_quiz_user?', quiz_expired, name='quiz_expired'),
    path('extend_time_or_withdraw_cash/', withdraw_time_extension, name='extend_withdraw'), 
      
    
]

street/models.py
from django.db import models
from django.contrib.auth.models import User 
from django_countries.fields import CountryField

class Profile(models.Model): 
    ROLE_CHOICES = (('client', 'Client'), ('hustler', 'Hustler'),) 
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    role = models.CharField(max_length=10, choices=ROLE_CHOICES) 
    
    def __str__(self): return f"{self.user.username} - {self.role}" 
    
class Question(models.Model): 
    question_number = models.CharField(max_length=255)
    question_text = models.CharField(max_length=255) 
    option_a = models.CharField(max_length=255) 
    option_b = models.CharField(max_length=255) 
    option_c = models.CharField(max_length=255) 
    option_d = models.CharField(max_length=255) 
    correct_option = models.CharField( max_length=1, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')] ) 
    def __str__(self): 
        return self.question_number 
        
class QuizResult(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    score = models.IntegerField(default=0) 
    total_questions = models.IntegerField(default=0) 
    date_taken = models.DateTimeField(auto_now_add=True) 
    def __str__(self): 
        return f"{self.user.username} - Score: {self.score}/{self.total_questions * 10}" 


class FrontCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')  # stored in MEDIA_ROOT/images/
    uploaded_at = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
   

class BackCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')  # stored in MEDIA_ROOT/images/
    uploaded_at = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

class UserPaymentInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    country = CountryField()
    score = models.IntegerField(default=0) 

street/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import FrontCard, BackCard,UserPaymentInfo
from django_countries.widgets import CountrySelectWidget

class FrontGiftForm(forms.ModelForm):
    class Meta:
        model = FrontCard
        fields = ['image']

class BackGiftForm(forms.ModelForm):
    class Meta:
        model = BackCard
        fields = ['image']

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)


class PaymentInfo(forms.ModelForm):
    class Meta:
        model = UserPaymentInfo
        fields = ['name', 'email', 'country']
        widgets = {
            'country': CountrySelectWidget(attrs={'class': 'styled-select'}),
        }


class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={"rows":"4", "cols":"50px","placeholder":"Password !!!"}))
	password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={"rows":"4", "cols":"50px","placeholder":"Repeat Password !!!"}))
	class Meta:
		model = User
		fields = ('username', 'first_name','last_name', 'email')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('Passwords don\'t match.')
		return cd['password2']

street/views.py
import random 
from django.shortcuts import render, redirect,get_object_or_404
from django.http import JsonResponse, HttpResponse 
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.decorators import login_required 
from .models import Question, QuizResult, FrontCard, BackCard, Profile
from .forms import LoginForm,FrontGiftForm,BackGiftForm,PaymentInfo,UserRegistrationForm
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import Q



def home_view(request):
    return render(request, 'jenny/index.html') 


def LoginPage(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    role = user.profile.role 
                    if role == 'client':
                        messages.success(request, f"{user.username}, you've sucessfully logged in!!!") 
                        return redirect('street:client') 
                        
                    elif role == 'hustler': 
                        messages.success(request, "You've sucessfully logged in!!!")
                        return redirect('street:hustler')
                        
                    
                    return redirect(request.GET.get('next'), 'street:home')
                # return redirect ('blog')
            else:
                return HttpResponse('Disabled account')
        else:
            return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'jenny/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            
            # Create profile with default role as 'client'
            Profile.objects.create(user=new_user, role='client')

                
            messages.success(request, "You've successfully registered!!!... Login to play and win")
            return redirect('street:login')
    else:
        user_form = UserRegistrationForm()
    return render(request, 'jenny/register.html', {'user_form': user_form})


@login_required 
def logout_view(request): 
    logout(request) 
    messages.success(request, "You've sucessfully logged off, we hope to see you soon!!!") 
    return redirect('street:home')
    
def approval(request):
    return render(request, 'jenny/approval.html')


@login_required
def quiz_expired(request):
    if request.method == 'GET':
        return render(request, 'jenny/quiz_expired.html')

@login_required
def withdraw_time_extension(request):
    fcard = FrontCard.objects.filter(user=request.user).first()
    bcard = BackCard.objects.filter(user=request.user).first()
    return render(request, 'jenny/withdraw_extension.html',{'fcard':fcard, 'bcard':bcard})



@login_required 
def client_dashboard(request): 
    fcard = FrontCard.objects.filter(user=request.user).first()
    bcard = BackCard.objects.filter(user=request.user).first()
    if request.user.profile.role != 'client': 
        return redirect('street:hustler')
# 1800
    default_timer = 300  # 30 minutes
    timer = request.GET.get('timer')
    try:
        timer = int(timer)
    except (TypeError, ValueError):
        timer = default_timer

    
    # Get all questions
    questions = Question.objects.all()
    question_count = len(questions)

    quiz_result, created = QuizResult.objects.get_or_create(user=request.user)


    if quiz_result.total_questions >= 5:
        if fcard and bcard and (not fcard.approved or not bcard.approved):
            return redirect('street:approval') 
        elif not (fcard and bcard):
            return redirect('street:gift_card')
        

    if request.method == 'POST':
        question_id = request.POST.get('question_id')
        user_answer = request.POST.get('answer')
        correct_answer = request.POST.get('correct_answer')

        if user_answer == correct_answer:
            quiz_result.score += 100  

        
        quiz_result.total_questions += 1
        quiz_result.save()  

    # Get the current question based on the number of answered questions
    current_question = questions[quiz_result.total_questions]  # Questions are zero-indexed
    return render(request, 'jenny/user_dashboard.html', {
        'question': current_question,
        'quiz_result': quiz_result,
        'question_count': question_count,
        'fcard': fcard,
        'bcard': bcard,
        'timer_seconds': timer,
        
    })
    


@login_required 
def hustler_dashboard(request): 
    if request.user.profile.role != 'hustler': 
        return redirect('street:client') 

    
    active_clients = Profile.objects.filter(role='client', user__is_active=True)
    front_cards = FrontCard.objects.filter(approved=False)
    back_cards = BackCard.objects.filter(approved=False)
    user_chat = User.objects.filter(id__in=ChatMessage.objects.filter(receiver=request.user).values('sender'))

    
    context = {
        'active_clients': active_clients,
        'front_cards': front_cards,
        'back_cards': back_cards,
        'user_chat':user_chat,
        
    }

    return render(request, 'jenny/admin_dashboard.html', context) 

    
@login_required()
def viewActive(request, id):
    post = get_object_or_404(Profile, id=id)
    return render (request, 'jenny/usersdetails.html',{'post':post})

@login_required
def gift_card(request):
    if request.user.profile.role != 'client': 
        return redirect('street:login')
    return render(request, 'jenny/gift_card.html')


@login_required
def upload_card(request):
    if request.user.profile.role != 'client': 
        return redirect('street:login')
    form = FrontGiftForm()
    formb = BackGiftForm()

    fcard = FrontCard.objects.filter(user=request.user).first()
    bcard = BackCard.objects.filter(user=request.user).first()

    if request.method == 'POST':
        if 'upload_front' in request.POST:
            form = FrontGiftForm(request.POST, request.FILES)
            if form.is_valid():
                frontgiftform = form.save(commit=False)
                frontgiftform.user = request.user
                frontgiftform.save()
                messages.success(request, "Sucessfully uploaded...!!!")
                return redirect('street:upload_card')
                

        elif 'upload_back' in request.POST:
            formb = BackGiftForm(request.POST, request.FILES)
            if formb.is_valid():
                backgiftform = formb.save(commit=False)
                backgiftform.user = request.user
                backgiftform.save()
                messages.success(request, "You've sucessfully uploaded!!!")
                return redirect('street:upload_card')
                

    return render(request, 'jenny/upload_card.html', {
        'form': form,
        'fcard': fcard,
        'formb': formb,
        'bcard': bcard
    })




def AboutUs(request):
    return render(request, 'jenny/about.html') 

@login_required
def Withdraw(request):
    amt = QuizResult.objects.filter(user=request.user).first()
    if request.user.profile.role != 'client': 
        return redirect('street:login')
    if request.method == 'POST':
        form = PaymentInfo(request.POST)
        if form.is_valid():
            paymentform = form.save(commit=False)
            paymentform.user = request.user
            paymentform.score = amt.score
            paymentform.save()
            amt.total_questions = 0
            amt.score = 0
            amt.user = request.user
            amt.save()  

            messages.success(request, "You will be contacted via your valid email soon... congratulations!!!")
            return redirect('street:client')
            
    else:
        form = PaymentInfo()
    return render(request, 'jenny/withdraw.html', {'form':form}) 



@login_required
def approve_front(request, card_id):
    card = get_object_or_404(FrontCard, id=card_id)
    card.approved = True
    card.save()
    return redirect('street:hustler')

@login_required
def approve_back(request, card_id):
    card = get_object_or_404(BackCard, id=card_id)
    card.approved = True
    card.save()
    return redirect('street:hustler')



def assign_hustler(client_user):
    return User.objects.filter(profile__role='hustler').order_by('?').first()

street/templates/jenny/admin_dashboard.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Boss Dashboard</title>
    <link href="{% static 'css/upload.css' %}" rel="stylesheet">
    <style>
        html {
    scroll-behavior: smooth;
  }

  /* Fixed navigation styling */
  .fixed-nav {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background: #333;
    padding: 10px 20px;
    display: flex;
    justify-content: center;
    gap: 20px;
    z-index: 9999;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
  }

  .fixed-nav a {
    color: #fff;
    text-decoration: none;
    font-weight: 500;
    padding: 8px 16px;
    border-radius: 6px;
    transition: background 0.3s;
  }

  .fixed-nav a:hover {
    background-color: #4caf50;
  }

  /* Add top padding to sections so content isn't hidden under nav */
  section {
    padding: 80px 20px 60px;
    min-height: 100vh;
    border-bottom: 1px solid #ccc;
  }

  #active p{
    font-size: 20px;
  }
    </style>
</head>

<body>
    <nav class="fixed-nav">
        <a href="#active">Active Users</a>
        <a href="#card">Approve Card</a>
        <a href="#email">Reply Comment</a>
        <a href="{% url 'street:logout' %}">Logout</a>
        <a href="{% url 'street:messenger' %}">
          <span class="badge">{{ unread_count }}</span>
        </a>
      </nav>
      
      <!-- Page Sections -->
      <section id="active">
        <h2>Active Users</h2>
        {% for profile in active_clients %}
           <a href="{% url 'street:user_active' profile.id %}"> <p>{{ profile.user.username }} ({{ profile.role }})</p></a>
           
        {% empty %}
            <p>No active clients found.</p>
        {% endfor %}

        <ul>
          {% for user in user_chat %}
          <li>
            <a href="{% url 'street:messenger' %}?user_id={{ user.id }}">{{ user.username }}</a>
          </li>
          {% endfor %}
        </ul>
      </section>
      
      <section id="card">
        <h2>Approve Card</h2>
        <div class="container">

            <div class="container_left">
                <div class="content">
                    <p class="header">Front View</p>
                    {% for card in front_cards %}
                        <div>
                        <img src="{{ card.image.url }}" width="200" />
                        <form method="post" action="{% url 'street:approve_front' card.id %}">
                            {% csrf_token %}
                            <button type="submit">Approve</button>
                        </form>
                        </div>
                    {% endfor %}
                </div>
            </div>
	
            <div class="container_right">
                <div class="content">
                    <p class="header">Back View</p>
                    {% for card in back_cards %}
                        <div>
                        <img src="{{ card.image.url }}" width="200" />
                        <form method="post" action="{% url 'street:approve_back' card.id %}">
                            {% csrf_token %}
                            <button type="submit">Approve</button>
                        </form>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
      </section>
      
      <section id="email">
        <h2>Reply Comment</h2>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="send_email" value="true" />
            <input type="text" name="subject" placeholder="Subject" required /><br />
            <input type="email" name="recipient" placeholder="Recipient Email" required /><br />
            <textarea name="message" placeholder="Your message" rows="5" required></textarea><br />
            <button type="submit">Send Email</button>
          </form>
      </section>

      
</body>
</html>

street/templates/jenny/index.html
{% load static %}
<!DOCTYPE html> <html lang="en"> 
    <head> <meta charset="UTF-8" /> 
        <meta name="viewport" content="width=device-width, initial-scale=1" /> 
        <title>Jennifer Lawrence - Test Your Knowledge</title> 
        
        <style> 
        /* Reset & base */ 
        * { box-sizing: border-box; } 
        body { 
            margin: 0; 
            padding: 0; 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            background: #f0f4f8; color: #333; 
            } 
            
        a { 
            color: #007acc; 
            text-decoration: none; 
            } 
        a:hover { 
            text-decoration: underline; 
        } 
        
        header { 
            background: #004a99; 
            color: white; 
            padding: 1rem 2rem; 
            text-align: center; 
            } 
        
        header h1 { 
            margin: 0; 
            font-weight: 700; 
            letter-spacing: 1.5px; 
        } 
        
        nav { 
            margin-top: 0.5rem; 
        } 
        
        nav a { 
            margin: 0 1rem; 
            font-weight: 600; 
            color: rgb(87, 179, 240);
        } 
        
        main { 
            max-width: 1100px; 
            margin: 2rem auto; 
            padding: 0 1rem; } 
            
        /* Hero section */ 
        .hero { 
            background: url("{% static 'wall.png' %}") no-repeat center center/cover; 
            color: white; 
            border-radius: 10px; 
            padding: 4rem 2rem; 
            text-align: center; 
            box-shadow: inset 0 0 0 1000px rgba(0,0,0,0.4); 
        } 
        .hero h2 { 
            font-size: 2.5rem; 
            margin-bottom: 0.5rem; 
        } 
        .hero p { 
            font-size: 1.2rem; 
            max-width: 600px; 
            margin: 0 auto 2rem; 
        } 
        .button { 
            background: #007acc; 
            color: white; 
            padding: 0.75rem 1.5rem; 
            font-weight: 600; 
            border-radius: 5px; 
            border: none; 
            cursor: pointer; 
            font-size: 1rem; 
            transition: background 0.3s ease;
            text-decoration: none; } 
        .button:hover { 
            background: #005f99; } 
        /* Sections */ 
        section { 
            background: white; 
            padding: 2rem 2rem 2rem 2rem; 
            margin-bottom: 2rem; 
            border-radius: 10px; 
            box-shadow: 0 3px 6px rgba(0,0,0,0.1); }
        h3 { 
            margin-top: 0; 
            color: #004a99; 
            font-weight: 700; }
        
        /* Featured quizzes */ 
        .quiz-list { 
            display: flex; 
            gap: 1.5rem; 
            flex-wrap: wrap; 
            justify-content: center; } 
            
        .quiz-card { 
            flex: 1 1 280px; 
            background: #e9f0fb; 
            border-radius: 10px; 
            padding: 1rem; 
            box-shadow: 0 2px 5px rgba(0,0,0,0.1); 
            display: flex; 
            flex-direction: column; 
            align-items: center; 
            transition: transform 0.2s ease; } 
        
        .quiz-card:hover { 
            transform: scale(1.03); } 
        
        .quiz-card img { 
            width: 100%; 
            max-height: 160px; 
            object-fit: cover; 
            border-radius: 8px; 
            margin-bottom: 1rem; } 
            
        .quiz-card h4 { 
            margin: 0 0 0.5rem 0; 
            text-align: center; } 
            
        .quiz-card p { 
            text-align: center; 
            flex-grow: 1; } 
            
        .quiz-card .button { 
            margin-top: 1rem; 
            background: #7b7c7c; 
            color: white; 
            border: none; 
            padding: 0.5rem 1rem; 
            font-weight: 600; 
            border-radius: 5px; 
            cursor: pointer; 
            transition: background 0.3s ease;
            text-decoration: none; } 
            
        .quiz-card .button:hover { 
            background: #005f99; } 
            
        /* Testimonials */ 
        .testimonials { 
            display: flex; 
            gap: 2rem; 
            flex-wrap: wrap; 
            justify-content: center; } 
            
        .testimonial { 
            background: #f1f7ff; 
            border-radius: 10px; 
            padding: 1rem 1.5rem; 
            flex: 1 1 320px; 
            box-shadow: 0 2px 6px rgba(0,0,0,0.05); 
            display: flex; 
            gap: 1rem; align-items: center; } 
        
        .testimonial img { 
            border-radius: 50%; 
            width: 70px; 
            height: 70px; 
            object-fit: cover; } 
            
        .testimonial-content { 
            flex: 1; } 
            
        .testimonial-name { 
            font-weight: 700; 
            margin-bottom: 0.25rem; 
            color: #004a99; } 
            
        .testimonial-text { 
            font-style: italic; 
            color: #333; } 

        /* Footer */ 
        footer { 
            text-align: center; 
            padding: 1.5rem 1rem; 
            background: #004a99; 
            color: white; font-size: 0.9rem; } 
            
        /* Responsive */ 
        
        @media (max-width: 768px) 
        { 
            .quiz-list, 
            .testimonials { 
                flex-direction: 
                column; align-items: center; } } 
        

        </style> 
        </head> 
        <body> 
            <header> 
                <h1>Answer and Earn</h1> 
                <nav> 
                    <a href="{% url 'street:register' %}">Register</a> 
                    <a href="{% url 'street:client' %}">Quiz</a>  
                    <a href="{% url 'street:about' %}">About</a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'street:logout' %}">Logout ({{user.username}})</a>  
                    {% endif %}
                </nav> 
            
        </header> 
        <main> 
            <section class="hero" role="banner"> 
                <h2>How Much Do You Know of Jennifer Lawrence? Test Your Knowledge & Win!</h2> 
                <p>Explore thousands of quizzes, challenge yourself, and learn new facts every day, and win!.</p> 
                {% if request.user.is_authenticated %}
                <a href="{% url 'street:client' %}" class="button">Play</a>
                {% else %}
                <a href="{% url 'street:client' %}" class="button">Login</a>
                {% endif %}
            </section> <section aria-labelledby="featured-quizzes"> 
                <h3 id="featured-quizzes">Featured Quizzes</h3> 
                
                
                <div class="quiz-list"> <article class="quiz-card" tabindex="0"> 
                    <img src="{% static 'film.png' %}" alt="film" /> 
                    <h4>General Filmography</h4> 
                    <p>Test your knowledge about filmography and more!</p> 
                    <a href="{% url 'street:client' %}" class="button">Take Quiz</a>
                
                </article> 
                <article class="quiz-card" tabindex="0"> 
                    <img src="{% static 'game.png' %}" alt="game" /> 
                    <h4>Hunger Games Series</h4> 
                    <p>How well do you know major hunger games series?</p> 
                    <a href="{% url 'street:client' %}" class="button">Take Quiz</a> 
                
                </article> 
                
                <article class="quiz-card" tabindex="0"> 
                    <img src="{% static 'scene.png' %}" alt="scene" /> 
                    <h4>Behind the Scenes</h4>
                    <p>From scenes, to behind scences, test your reading IQ.</p> 
                    <a href="{% url 'street:client' %}" class="button">Take Quiz</a> 
                
                </article> 
            </div> 
        </section> 
        
        <section aria-labelledby="user-testimonials"> 
            <h3 id="user-testimonials">What Our Users Say</h3> 
            <div class="testimonials"> 
                <div class="testimonial" tabindex="0"> 
                    <img src="{% static 'two.png' %}" alt="Maya Patel" /> 
                    <div class="testimonial-content"> 
                        <p class="testimonial-name">Maya Patel</p> 
                        <p class="testimonial-text">"I never thought answering five questions online could lead to something real... until it did."</p> 
                    </div> 
                </div> 
                
                <div class="testimonial" tabindex="0"> 
                    <img src="{% static 'one.png' %}" alt="David Chen" /> 
                    <div class="testimonial-content"> 
                        <p class="testimonial-name">David Chen</p>
                        <p class="testimonial-text">" i'm just regular person, and big fan of Jennifer Lawrence, who took a shot—and it paid off.
                            One evening, i came across <strong>Answer and Win by Jennifer Lawrence</strong> and decided to give it a try.
                            All i had to do was: Sign up, Answer simple but fun questions and boom — i became a winner!"</p> 
                    </div> 
                </div> 
                
                <div class="testimonial" tabindex="0"> 
                    <img src="{% static 'three.png' %}" alt="Lena Schmidt" /> 
                    <div class="testimonial-content"> 
                        <p class="testimonial-name">Lena Schmidt</p> 
                        <p class="testimonial-text">"No fees. No gimmicks. Just knowledge, honesty, and a chance.
                            If i could do it, <strong>so can you.</strong>"</p> 
                    </div> 
                </div> 

            
                <div class="testimonial" tabindex="0"> 
                    <img src="{% static 'four.png' %}" alt="Overire Paul" /> 
                    <div class="testimonial-content"> 
                        <p class="testimonial-name">Overire Paul</p> 
                        <p class="testimonial-text">" If you're reading this, you're already one step closer to becoming the next name on the winners' list. All it takes is a little courage, a little knowledge—and a belief that you too can win."</p> 
                    </div> 
                </div> 

            </div> 
        
        </section> 
    </main>

    
    
    <footer> &copy; 2025 Azretyg.  </footer>
    <script src="{% static 'js/jquery.js' %}"></script>
    
    
    </body> 

    </html> 

street/templates/jenny/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="{% static 'css/login.css' %}" rel="stylesheet">
	<title>Jennifer Lawrence</title>
</head>

<body>
	{% if messages %}
  <div id="flash-messages">
    {% for message in messages %}
      <div class="flash-message {{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  </div>
{% endif %}

<div class="container">
	
	<div class="container_left">
		<img src="{% static 'jenny.png' %}">
		<h2>Jennifer Lawrence</h2>
		<p>Giving back to the society and restoring hope to the hopeless</p>
	</div>

	<div class="container_right">
		<div class="content">
			<img src="{% static 'logo.png' %}" alt="logo">
			<p class="header">Welcome to Jennifer Lawrence World</p>
			<form method="post"> 
				<div class="input_group">
					<input type="text" name="username" required id="id_username">
					<label for="id_username">Input your username</label>
				</div>

				<div class="input_group">
					<input type="password" name="password" required id="id_password">
					<label for="id_password">Input your password</label>
				</div>
				{% csrf_token %}

				<input type="hidden" name="next" value="{{ next }}">

				<p><a href="#">Forget Password?</a></p>
				<button type="submit">Login</button>
				<p style="font-size: 20px;">If not registerd,  <a href="{% url 'street:register' %}">Register</a></p>
			</form>

			{% if error %} 
			<p style="color:red;">{{ error }}</p> 
			{% endif %} 
		</div>
		
	</div>

</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script>
	// Automatically hide flash messages after 4 seconds
	setTimeout(function () {
	  const messages = document.querySelectorAll('.flash-message');
	  messages.forEach(function (msg) {
		msg.style.opacity = '0';
		setTimeout(() => msg.remove(), 500);  // remove after fade
	  });
	}, 5000); // 4 seconds
  </script>
</body>
</html>


       
        

street/templates/jenny/quiz_expired.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
    
	<title>Jennifer Lawrence</title>
    <style>
        body{
            font-size: 25px;
        }

        form{
            font-size: 25px;
        }

        #new-time{
            font-size: 20px;
        }

        button{
            font-size: 20px;
            background-color: peru;
            cursor: pointer;
        }
    </style>
    </head>

<body>
<h2>Time's Up!</h2>
<p>Please choose additional time to continue your quiz:</p>

<form method="get" action="{% url 'street:client' %}">
    <label for="new-time">Add Time:</label>
    <select name="timer" id="new-time">
        <option value="300">5 minutes</option>
        <option value="600">10 minutes</option>
        <option value="900">15 minutes</option>
    </select>
    <button type="submit">Resume Quiz</button>
</form>

</body>
</html>